name: Security Scans

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    # Scan Dockerfile for security issues
    - name: Scan Dockerfile with Hadolint
      uses: docker://hadolint/hadolint
      with:
        dockerfile: Dockerfile

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2